Coffeemachine task
zvykach/NIX_java_education_Kuzmenko_Andriy pull request #3
Opened 2021-11-10 18:39 UTC by zvykach

2021-11-11 18:06 UTC, maxsomochkin requested changes

2021-11-11 18:06 UTC, maxsomochkin commented on src/nix/education/java/coffeemachine/CoffeeMachine.java
> +        money += stats.PRICE;
Вынеси if-ы в отдельный метод

2021-11-11 18:06 UTC, maxsomochkin commented on src/nix/education/java/coffeemachine/CoffeeMachine.java
> +                    }
Старайся не помещать под кейс много логики. вынеси блок try в отдельный метод

2021-11-11 19:56 UTC, maxsomochkin requested changes

2021-11-11 19:56 UTC, maxsomochkin commented on src/nix/education/java/coffeemachine/CoffeeMachine.java
> +        water -= stats.WATER; milk -= stats.MILK; coffeeBeans -= stats.COFFEE_BEANS;
НИКОГДА не определяй  и не переопределяй переменные в одну строку

2021-11-13 14:16 UTC, asrubel approved these changes

2021-11-14 12:53 UTC, merged