Hangman
zvykach/NIX_java_education_Kuzmenko_Andriy pull request #5
Opened 2021-11-19 19:55 UTC by zvykach

2021-11-20 09:48 UTC, maxsomochkin requested changes

2021-11-20 09:48 UTC, maxsomochkin commented on src/nix/education/java/hangman/Hangman.java
> +        this.gameProcess();
не стоит из конструктора запускать методы

2021-11-20 09:48 UTC, maxsomochkin commented on src/nix/education/java/hangman/Hangman.java
> +            }
Не используй   System.exit(0); программа должна завершаться сама. пререпиши цикл где устовие в нем поставь, например while (isNotExit). А в тееле цикла назначай этой переменной false

2021-11-20 09:48 UTC, maxsomochkin commented on src/nix/education/java/hangman/Hangman.java
> +        while (true) {
создай метод в классе Game. И вызывай его из созданного обекта Game

2021-11-20 09:48 UTC, maxsomochkin commented on src/nix/education/java/hangman/Hangman.java
> +            Pair<TargetWord.CheckResult, Integer> result = targetWord.checkLetter(input.charAt(0));
Вынеси свич в отдельный метод

2021-11-22 15:15 UTC, asrubel commented on src/nix/education/java/hangman/Hangman.java
> +    private static final Scanner SCANNER = new Scanner(System.in);
делай пустые линии между свойствами - так более читаемо будет

2021-11-22 15:31 UTC, asrubel approved these changes

2021-11-23 14:25 UTC, merged