DinnerParty
zvykach/NIX_java_education_Kuzmenko_Andriy pull request #7
Opened 2021-11-30 20:55 UTC by zvykach

2021-12-01 13:56 UTC, maxsomochkin requested changes

2021-12-01 13:56 UTC, maxsomochkin commented on src/nix/education/java/dinner/party/DinnerParty.java
> +public class DinnerParty {
Создай отдельный класс DinnerParty и помести туда все методы. Здесь сделай Main класс в котором будет только маин метод в котором создашь обект класса DinnerParty. И оттуда будешь вызывать все методы

2021-12-01 13:56 UTC, maxsomochkin commented on src/nix/education/java/dinner/party/DinnerParty.java
> +    private static final Random RANDOM = new Random();
Все утилитные обьекты создавай внутри классов и методов. Избавься от статиков

2021-12-01 13:56 UTC, maxsomochkin commented on src/nix/education/java/dinner/party/DinnerParty.java
> +    private static void process() {
Все статические методы перепиши в обычные в классы

2021-12-05 17:03 UTC, asrubel approved these changes

2021-12-05 18:00 UTC, merged